name: Publish HTML to Storage Account

on:
  workflow_dispatch

jobs:
  generate-html-files:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: Copy files to articles folder
      shell: pwsh
      run: Copy-Item 'FINU/', 'DOCUSIGN/', 'DXC-INSIGHTS', 'CORE-EXTENSIONS/', 'SMART-SEND/', 'FOREX-CONTRACT/', 'EDI/' 'build\dxcproducthelp\DXCDocFX\DXCDocFX\articles\' -Recurse
    - uses: nuget/setup-nuget@v1
    - name: Restore nuget packages
      run: nuget restore build\dxcproducthelp\DXCDocFX\DXCDocFX.sln
    - uses: microsoft/setup-msbuild@v1.1.3
    - name: Convert Mardown to Html
      run: msbuild build\dxcproducthelp\DXCDocFX\DXCDocFX\DXCDocFX.csproj -t:rebuild -verbosity:diag -property:Configuration=Debug
    - uses: actions/upload-artifact@master
      with:
        path: build\dxcproducthelp\DXCDocFX\DXCDocFX
        name: DXCProductHelpHTMLContent

  publish-to-storage-account:
    needs: [generate-html-files]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@master
        with:
          name: DXCProductHelpJSONContent
          path: build\dxcproducthelp\DXCDocFX\DXCDocFX\_site\articles
      - uses: bacongobbler/azure-blob-storage-upload@main
        with:
          source_dir: 'build\dxcproducthelp\DXCDocFX\DXCDocFX\_site\articles'
          container_name: ${{ secrets.TESTDXCPRODUCTHELPBLOBSTORAGECONTAINERNAME }}
          connection_string: ${{ secrets.TESTDXCPRODUCTHELPBLOBSTORAGECONNECTIONSTRING }}
          name: Upload to blob storage
          overwrite: true
